# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/morning',
                'doc_host': 'https://ja6od.github.io',
                'git_url': 'https://github.com/ja6od/morning',
                'lib_path': 'morning'},
  'syms': {'morning.core': {'morning.core.foo': ('core.html#foo', 'morning/core.py')}}}
